### ISSUE TITLE
Android version

### ISSUE THREAD

**Issue by Geal** [Geal/PilotSSH-scripts#10]
Here is the tracking issue for the Android version of Pilot SSH.

I will post updates on its development regularly. I will need beta testers soon, so if anyone is up for the task, please speak up :wink:

**Comment by jmvldz** [comment]
I will beta test!

**Comment by Geal** [comment]
Thanks! I will notify it here when a beta version is available!

**Comment by Geal** [comment]
A small update: the Android app is going well. I have implemented the SSH connection, script execution and result display, but the DB has the bare minimum. And the graphism is... well, inexistant :wink: 

I will probably propose a beta version once it has all the needed features, and work on the tutorial part afterwards.

**Comment by Crupuk** [comment]
I can test to.  I can't wait

**Comment by Geal** [comment]
An update on the Android version: I have made good progress, and it is almost complete feature wise. The scripts can be used perfectly, and authentication works with password and public key.

The script upload is not yet implemented, but the application can already be tested.

Cf http://pilotssh.com/pages/android-beta for more information.

**Comment by Geal** [comment]
The script upload is done, and the app is getting stable. I have made good progress these days :)

**Comment by Geal** [comment]
The Android version is now available. You can download it at https://play.google.com/store/apps/details?id=com.gcouprie.pilotssh :)
