### ISSUE TITLE
maximum size of  JSON message too low.

### ISSUE THREAD

**Issue by zu2** [Geal/PilotSSH-scripts#18]
JSON message more than 8,193 bytes causes "Parse error  The script returned an empty string".　this limit be written somewhere?

So,

**Comment by Geal** [comment]
8k should not be a problem, normally. Is that for the process listing script? There might be a bug in there. Could you launch the script from command line, then paste the output in http://jsonlint.com/ ? It will help me fix the script.

**Comment by zu2** [comment]
I am testing on Linux (CentOS5) and iPhone 5. 

I test with simple script like this.

---

#!/bin/bash

## cat ~/.pilotssh/process/test.json.txt

At first, I use a  non error JSON file ( 8,145 bytes).
I added a blank to the file one by one. It became the error at 8,194 bytes.

Thanks.

**Comment by Geal** [comment]
I just tested with a 17 Kb file, and it's running fine. Could you provide me with your file, so that I can fix it?

**Comment by zu2** [comment]
I want to send a file for debugging. How do I send the file?

**Comment by Geal** [comment]
Please send it to contact@pilotssh.com

**Comment by Geal** [comment]
I just released the version 1.1.0, and it seems the bug is not present in this version. Could you try to update? (This version was in review when you posted the issue).

**Comment by zu2** [comment]
I just upgrade to version 1.1.0, that works fine. thanks.

**Comment by Geal** [comment]
I'm glad to hear it :smile: 

Don't hesitate to come back to me if you have other issues!
