### ISSUE TITLE
bad base-64

### ISSUE THREAD

**Issue by KalleDK** [Geal/PilotSSH-scripts#23]
I "hope" this is a bug..

I have the following script

[km@nas01 ~/.pilotssh/uname]$ ./uname 
{ "version": 1, "title": "Uname", "type":"text", "text":"UNAME" }

On the mobilephone i get this respond
decoding error: bad base-64

(My guess is something UTF / ANSI get mixed up)

Though if I do it as a status, then everything works as intended.

**Comment by Geal** [comment]
The 'text' attribute expects base64 encoded data. I chose that way to solve a lot of encoding problem. See https://github.com/Geal/PilotSSH-scripts/blob/master/logs/logs_show.sh for an example of how to display the results.

**Comment by KalleDK** [comment]
Oh thanks you

I would suggest change

https://github.com/Geal/PilotSSH-scripts/blob/master/API.md#text

So it would explain that it expects base64

**Comment by Geal** [comment]
It's done. Thanks for the suggestion!
