### ISSUE TITLE
Double listing of Echo for no apparent reason.

### ISSUE THREAD

**Issue by fjrichman** [Geal/PilotSSH-scripts#26]
I deleted everything in ~/.pilotssh/ using "rm -rf *" while in the folder, I then went up one level to ~/ and used "git clone https://github.com/Geal/PilotSSH-scripts.git .pilotssh" to copy new files from the repository into the .pilotssh folder.

For some reason the Echo command appears twice now in my list, upon looking at the script folder for echo there appears to be no reason that it would be listing twice.
![screenshot_2013-07-20-13-38-43](https://f.cloud.github.com/assets/5055387/830819/78661bcc-f17c-11e2-9f27-74a563a6870c.png)

**Comment by Geal** [comment]
Looking into it right now. That is a weird bug :D
