### ISSUE TITLE
PilotSSH Kit Kat Crash

### ISSUE THREAD

**Issue by fjrichman** [Geal/PilotSSH-scripts#28]
I'm attempting to run PilotSSH on KitKat build KRT16S on a Nexus 4. I'm rooted, and running the Xposed Framework. It crashes immediately. I'll provide more information if you need it, but it would seem the PilotSSH is incompatible with Kitkat on Nexus 4.

**Comment by fjrichman** [comment]
https://github.com/sqlcipher/android-database-sqlcipher/issues/107

Gives the same sort of errors I'm seeing and gives a solution.

**Comment by Geal** [comment]
Thanks for the report! I just pushed a new version to the store, with an updated SQLCipher. Let me now if it works for you.
