### ISSUE TITLE
Run as sudo

### ISSUE THREAD

**Issue by Geekfish** [Geal/PilotSSH-scripts#7]
While accessing a server with a user that is in the sudoers, you should be able to run  commands with sudo without having to log in as root.

**Comment by Geal** [comment]
I have some code to support sudo usage, but it was not stable enough to be included in the first release. The code is different, because with LibSSH2, it is rather easy to send one command and get the result, but it needs a lot more code for an interactive command like sudo.
Would you like to beta test the sudo code? If you send me your UDID, I can build a version of the application supporting sudo, and send it to you.

**Comment by Geekfish** [comment]
I can do that yes! Would it be ok if I email the UDID to you instead, I would prefer not to publish on github, is there an email I can send it to?
Many thanks for coming back so quickly :+1:

**Comment by Geal** [comment]
Yes, email is ok. You can find the support email at the end of the http://pilotssh.com/ webpage.

**Comment by xenji** [comment]
Why is sudo meant to be interactive? I run my nagios checks from one specific user who is able to use sudo without a password for only the check commands. This would mean you can emit the sudo command like any other command, wouldn't it?

**Comment by Geal** [comment]
It can be done that way, but for most users, sudo without password is not
an option. They appreciate the additional protection of asking for a
password.

Moreover, I want to provide a no-configuration experience: you connect,
upload the scripts, and you can get rolling.

**Comment by xenji** [comment]
Ok, the zero config idea is fine for me, but using a explicit nopasswd /path/to/binary is no magic at all. In fact, this is very common for nagios/cacti/munin checks.

**Comment by Geal** [comment]
Yes, that's probably how I would do it too :)

Feel free to use it that way, then! You just need to replace the call to
".pilotssh/folder/script" by "sudo .pilotssh/folder/script".

**Comment by Geal** [comment]
Sudo works in the Android version. Sudo supports will come in the next update for the iOS version.

**Comment by Geal** [comment]
A new iOS version was published, with sudo support.
